version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: CP_test_db
      MYSQL_USER: CP_flask_app
      MYSQL_PASSWORD: qwerty
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./SQL_scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  web:
    build: .
    restart: always
    environment:
      SECRET_KEY: XNBzeuqo+zcYg4l9g17zLbKezSuONQikby7jvOVsnKhcixDlVGm0pCtCzqda6iel
      MYSQL_HOST: db
      MYSQL_DATABASE: CP_test_db
      MYSQL_USER: CP_flask_app
      MYSQL_PASSWORD: qwerty
      SESSION_PERMANENT: False
      SESSION_TYPE: filesystem
    volumes:
      - ./users_file_storage:/app/users_file_storage
      - ./flask_session:/app/flask_session
    depends_on:
      - db
    networks:
      - app-network
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/app/static:ro
      - ./users_file_storage:/app/users_file_storage:ro
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  flask_session:
